create table users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null,
    full_name varchar(255) not null,
    password varchar(255) not null,
    role varchar(255) not null,
    constraint uk_users_email unique (email),
    constraint users_role_check check (role in ('USER', 'ADMIN'))
);

create table accounts (
    id bigint generated by default as identity primary key,
    account_number varchar(32) not null,
    balance numeric(19, 2) not null,
    created_at timestamp with time zone not null,
    currency varchar(3) not null,
    status varchar(255) not null,
    user_id bigint not null,
    constraint uk_accounts_account_number unique (account_number),
    constraint accounts_status_check check (status in ('ACTIVE', 'FROZEN', 'CLOSED')),
    constraint fk_accounts_user foreign key (user_id) references users (id)
);

create index idx_accounts_user_id on accounts (user_id);

create table transactions (
    id bigint generated by default as identity primary key,
    amount numeric(19, 2) not null,
    created_at timestamp with time zone not null,
    currency varchar(3) not null,
    description varchar(255),
    status varchar(255) not null,
    type varchar(255) not null,
    from_account_id bigint not null,
    to_account_id bigint not null,
    constraint transactions_status_check check (status in ('COMPLETED', 'FAILED')),
    constraint transactions_type_check check (type in ('TRANSFER')),
    constraint fk_transactions_from_account foreign key (from_account_id) references accounts (id),
    constraint fk_transactions_to_account foreign key (to_account_id) references accounts (id)
);

create index idx_transactions_from_account_id on transactions (from_account_id);
create index idx_transactions_to_account_id on transactions (to_account_id);
create index idx_transactions_created_at on transactions (created_at);
