create table audit_logs (
    id bigint generated by default as identity primary key,
    action varchar(255) not null,
    actor_email varchar(255) not null,
    target_type varchar(100),
    target_id bigint,
    details varchar(500),
    created_at timestamp with time zone not null,
    constraint audit_logs_action_check check (action in (
        'USER_REGISTERED',
        'USER_LOGIN',
        'ACCOUNT_CREATED',
        'TRANSFER_COMPLETED',
        'ADMIN_ACCOUNT_FUNDED'
    ))
);

create index idx_audit_logs_created_at on audit_logs (created_at);
create index idx_audit_logs_actor_email on audit_logs (actor_email);
