create table refresh_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token_hash varchar(64) not null,
    expires_at timestamp with time zone not null,
    revoked boolean not null,
    created_at timestamp with time zone not null,
    constraint uk_refresh_tokens_token_hash unique (token_hash),
    constraint fk_refresh_tokens_user foreign key (user_id) references users (id)
);

create index idx_refresh_tokens_user_id on refresh_tokens (user_id);
create index idx_refresh_tokens_expires_at on refresh_tokens (expires_at);
