create table beneficiaries (
    id bigint generated by default as identity primary key,
    owner_user_id bigint not null,
    destination_account_id bigint not null,
    nickname varchar(80),
    created_at timestamp with time zone not null,
    constraint uk_beneficiaries_owner_destination unique (owner_user_id, destination_account_id),
    constraint fk_beneficiaries_owner foreign key (owner_user_id) references users (id),
    constraint fk_beneficiaries_destination_account foreign key (destination_account_id) references accounts (id)
);

create index idx_beneficiaries_owner_user_id on beneficiaries (owner_user_id);
create index idx_beneficiaries_destination_account_id on beneficiaries (destination_account_id);
